### ISSUE TITLE
ARMv7 cross-compiled failed to execute

### ISSUE THREAD

**Issue by jpvlerbe** [Azure/azure-storage-azcopy#1255]
I have followed the instructions in #415 to cross-compile on a ubuntu machine with go1.15.5 linux/amd64

```
go get github.com/Azure/azure-storage-azcopy
cd src/github.com/Azure/azure-storage-azcopy
env GOOS=linux GOARCH=arm go build
```

At the `go get` command I get the output:
```
# github.com/Azure/azure-storage-azcopy/common
src/github.com/Azure/azure-storage-azcopy/common/credentialFactory.go:249:9: undefined: minio.NewWithCredentials
```

The build after that however seems to execute without error.

When I then execute `azcopy login --tenant-id=<tenant>` on my armv7 device (a Synology NAS)
I get the device login but after logging in through the browser it crashes with:
```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code> to authenticate.


SIGILL: illegal instruction
PC=0xc467c m=2 sigcode=4
instruction bytes: 0x40 0x60 0x9f 0xe5 0x6 0x0 0x50 0xe1 0x7 0x0 0x0 0x9a 0x0 0x10 0xe0 0xe3

goroutine 1 [syscall]:
syscall.Syscall6(0x900137, 0x0, 0xfffffffd, 0x1, 0x0, 0x0, 0x0, 0xab0abc, 0x4, 0x3372180)
        /usr/local/go/src/syscall/asm_linux_arm.s:45 +0x8 fp=0x3407554 sp=0x3407550 pc=0xc465c
github.com/jiacfan/keyctl.keyctl(0x0, 0x34075c4, 0x2, 0x2, 0x0, 0x1000, 0xd93, 0x1000)
....

```

**Comment by zezha-msft** [comment]
Hi @jpvlerbe. Thanks for reaching out!

Unfortunately we do not support ARM. It looks like the problem may have come from the usage of keyring. I suggest maybe you could give the in-memory login a try. More info is in this [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)).
