### ISSUE TITLE
Typo in cmd/syncComparator.go causes build to fail

### ISSUE THREAD

**Issue by tla5** [Azure/azure-storage-azcopy#2423]
### Which version of the AzCopy was used? 

Attempting to build [v10.21.0](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.21.0)

### Which platform are you using? (ex: Windows, Mac, Linux)

Alpine Linux 3.17.0
Golang 1.19.3

### What command did you run?

```
git clone --depth 1 --branch v10.21.0 https://github.com/Azure/azure-storage-azcopy
cd azure-storage-azcopy
go build -o azcopy
```

### What problem was encountered?

What appears to be a typo introduced in #2372 causes errors upon trying to build AzCopy from source:

```
$ go build
# github.com/Azure/azure-storage-azcopy/v10/cmd
cmd/syncComparator.go:117:77: undefined: syncOverwriteResaonNewerLMT
```

### How can we reproduce the problem in the simplest way?

See above 

### Have you found a mitigation/solution?

Patching the file to fix the typo before building allows us to build the release successfully:

```
$ sed -i 's#syncOverwriteResaonNewerLMT#syncOverwriteReasonNewerLMT#g' cmd/syncComparator.go
$ go build -o azcopy
$ ./azcopy --version
azcopy version 10.21.0
```

It is apparently implemented in #2414

**Comment by gapra-msft** [comment]
Hi, this has been resolved in our dev branch, as part of our next release, we will merge changes in the dev branch into main. 
https://github.com/Azure/azure-storage-azcopy/blob/b90a900f05d17745dd3b87268d265a1c197f4802/cmd/syncComparator.go#L117

Closing this for now since we are aware and it will be resolved as part of the next release.
